name: E2E on Chrome

on:
  push:
    branches:
      - '**'  
  pull_request:
    types: [opened, reopened, edited, synchronize]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false


jobs:
  navigateToCareers-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cypress run
        uses: cypress-io/github-action@v6.6.1
        with:
          command: npm run test:navigateToCareers

  solutions-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cypress run
        uses: cypress-io/github-action@v6.6.1
        with:
          command: npm run test:solutions

 